### ISSUE TITLE
MLB Streams not working

### ISSUE THREAD

**Issue by Organikk** [nomego/Lazyman.bundle#51]
Hi there,

I'm not getting any errors, just that the stream will not load. It just sits there and spins. I've double checked the hosts file entries and that's fine. I know that works as NHL streams work fine.

Any ideas?

**Comment by ikwhite56** [comment]
Experiencing exact same thing NHL works fine, but MLB stream does not load little circle just keeps spinning when I try to load a game, Checked hosts file and some other settings direct stream etc... but no luck getting it to work.

**Comment by jasonmarquette** [comment]
I'm having the same issue where the mlb iisn't working, but nhl is.

@ikwhite56 Can you please share what you did to edit your hosts file that it wasn't correct? 
Mine looks like: 
```
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
188.240.208.152 mf.svc.nhl.com
188.240.208.152 mlb-ws-mf.media.mlb.com
```
Were the last 2 are the entries needed, I did try other domain that was listed and I saw reference that it will be going away in 2018. Additionally, it didn't resolve when I ping'd it anyway.

Thanks!

**Comment by ikwhite56** [comment]
Yeah Jason if you could remove the ip's from your post that would be great, for what ever readon they don't like you to publicly post the ip, You are missing playback.svcs.mlb.com!

**Comment by jasonmarquette** [comment]
Thank you. Sorry about that, I edited the comment. 


Sent from Yahoo Mail for iPhone


On Sunday, April 8, 2018, 12:30 PM, ikwhite56 <notifications@github.com> wrote:


Yeah Jason if you could remove the ip's from your post that would be great, for what ever readon they don't like you to publicly post the ip, You are missing playback.svcs.mlb.com!

**Comment by Menz01** [comment]
i am having the same issue. NHL does work but MLB do not i have this in my HOSTS file:

x.x.x.x  mf.svc.nhl.com
x.x.x.x  mlb-ws-mf.media.mlb.com

of course the "X's" have actial IP addresses

**Comment by jasonmarquette** [comment]
1. Add the playback svcs at the bottom where the ip address is the same as the others. Make sure it is saved. If on Linux -> cat /etc/hostsensure that it is exactly as below.
2. reboot your server (the OS itself), subsequently rebooting plex media server.
That should fix it.Post back and let me know.

Below is what is in my /etc/hosts (at the bottom), where the x.x.x.x represents the IP address.
 x.x.x.x mf.svc.nhl.com  x.x.x.x mlb-ws-mf.media.mlb.com x.x.x.x playback.svcs.mlb.com

    On Wednesday, April 18, 2018, 12:03:35 PM CDT, Menz01 <notifications@github.com> wrote:  
 
 
i am having the same issue. NHL does work but MLB do not i have this in my HOSTS file:

x.x.x.x mf.svc.nhl.com
x.x.x.x mlb-ws-mf.media.mlb.com

of course the "X's" have actial IP addresses

**Comment by s0calkpr21** [comment]
Hi everyone.  I was able to update the hosts with the proper IP per the instructions posted.  Unfortunately, I still can't get anything to play through my PC or anywhere else (been trying roku). All I get is the spinning circle.  Is there anything else I can do to troubleshoot this?

**Comment by ymgenesis** [comment]
Using Plex and all I get is the spinning circle, as well. Something is going on here which I think we're unable to fix through configuration.

**Comment by nwalke** [comment]
Please try with the latest plex server.  This is now working!
